// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {roadmaps} from '../models';
import {settings} from '../models';

export function AddNewSite(arg1:number):Promise<void>;

export function DeleteRoadmap(arg1:string):Promise<void>;

export function DeleteSite(arg1:roadmaps.Site):Promise<void>;

export function GetAvailableRoadmaps():Promise<Array<string>>;

export function GetMapLoader():Promise<roadmaps.MapLoader>;

export function GetPreferences():Promise<settings.Settings>;

export function GetRoadmapSites():Promise<roadmaps.SiteSlice>;

export function GetRoadmapTitle():Promise<string>;

export function LogNavigation(arg1:string):Promise<void>;

export function ModifyPreferences(arg1:string,arg2:any):Promise<void>;

export function ModifySiteByID(arg1:number,arg2:string,arg3:string):Promise<void>;

export function MoveDownSite(arg1:roadmaps.Site):Promise<void>;

export function MoveUpSite(arg1:roadmaps.Site):Promise<void>;

export function NewRoadmap():Promise<void>;

export function OpenLink(arg1:string):Promise<void>;

export function OpenRepoLink():Promise<void>;

export function RenameRoadmap(arg1:string,arg2:string):Promise<void>;

export function ResetPreference(arg1:string):Promise<void>;

export function SaveRoadmap():Promise<void>;

export function SaveSettings():Promise<void>;

export function SelectRoadmap(arg1:string):Promise<void>;

export function SwitchCompletedState(arg1:roadmaps.Site):Promise<void>;

export function Version():Promise<Array<any>>;
