// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableRoadmaps() {
  return window['go']['app']['App']['GetAvailableRoadmaps']();
}

export function GetMapLoader() {
  return window['go']['app']['App']['GetMapLoader']();
}

export function GetRoadmapSites() {
  return window['go']['app']['App']['GetRoadmapSites']();
}

export function GetRoadmapTitle() {
  return window['go']['app']['App']['GetRoadmapTitle']();
}

export function LogNavigation(arg1) {
  return window['go']['app']['App']['LogNavigation'](arg1);
}

export function SelectRoadmap(arg1) {
  return window['go']['app']['App']['SelectRoadmap'](arg1);
}
