// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {roadmaps} from '../models';

export function GetAvailableRoadmaps():Promise<Array<string>>;

export function GetMapLoader():Promise<roadmaps.MapLoader>;

export function GetRoadmapSites():Promise<roadmaps.SiteSlice>;

export function GetRoadmapTitle():Promise<string>;

export function SelectRoadmap(arg1:string):Promise<void>;
