// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewSite(arg1) {
  return window['go']['app']['App']['AddNewSite'](arg1);
}

export function DeleteRoadmap(arg1) {
  return window['go']['app']['App']['DeleteRoadmap'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['app']['App']['DeleteSite'](arg1);
}

export function GetAvailableRoadmaps() {
  return window['go']['app']['App']['GetAvailableRoadmaps']();
}

export function GetMapLoader() {
  return window['go']['app']['App']['GetMapLoader']();
}

export function GetPreferences() {
  return window['go']['app']['App']['GetPreferences']();
}

export function GetRoadmapSites() {
  return window['go']['app']['App']['GetRoadmapSites']();
}

export function GetRoadmapTitle() {
  return window['go']['app']['App']['GetRoadmapTitle']();
}

export function LogNavigation(arg1) {
  return window['go']['app']['App']['LogNavigation'](arg1);
}

export function ModifyPreferences(arg1, arg2) {
  return window['go']['app']['App']['ModifyPreferences'](arg1, arg2);
}

export function ModifySiteByID(arg1, arg2, arg3) {
  return window['go']['app']['App']['ModifySiteByID'](arg1, arg2, arg3);
}

export function MoveDownSite(arg1) {
  return window['go']['app']['App']['MoveDownSite'](arg1);
}

export function MoveUpSite(arg1) {
  return window['go']['app']['App']['MoveUpSite'](arg1);
}

export function NewRoadmap() {
  return window['go']['app']['App']['NewRoadmap']();
}

export function OpenLink(arg1) {
  return window['go']['app']['App']['OpenLink'](arg1);
}

export function OpenRepoLink() {
  return window['go']['app']['App']['OpenRepoLink']();
}

export function RenameRoadmap(arg1, arg2) {
  return window['go']['app']['App']['RenameRoadmap'](arg1, arg2);
}

export function ResetPreference(arg1) {
  return window['go']['app']['App']['ResetPreference'](arg1);
}

export function SaveRoadmap() {
  return window['go']['app']['App']['SaveRoadmap']();
}

export function SaveSettings() {
  return window['go']['app']['App']['SaveSettings']();
}

export function SelectRoadmap(arg1) {
  return window['go']['app']['App']['SelectRoadmap'](arg1);
}

export function SwitchCompletedState(arg1) {
  return window['go']['app']['App']['SwitchCompletedState'](arg1);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
